import type { Metadata } from "next";
import Header from "@/components/Header";
import "./globals.css";
import { bagoss } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-brand-black h-screen ${bagoss.className}`}
        suppressHydrationWarning={true}
      >
        <Header />
        <main className="p-5 mt-[86px] h-[calc(100vh_-_86px)]">{children}</main>
      </body>
    </html>
  );
}
